# -*- coding: utf-8 -*-
"""appx

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R9q7Udg5AXQvha7io_UAIpn4xMG_Z7Vg
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pydeck as pdk
import requests
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(page_title="PriceWise", layout="wide")


# STYLE

st.markdown("""
<style>
    .stApp {
        background: #f5f7fb;
    }

    section[data-testid="stSidebar"] {
        background: #0f172a;
        border-right: 1px solid #1e293b;
    }

    section[data-testid="stSidebar"] * {
        color: #f8fafc !important;
    }

    h1, h2, h3 {
        color: #0f172a;
        letter-spacing: -0.02em;
    }

    p, div, label {
        color: #334155;
    }

    div[data-testid="metric-container"] {
        background: white;
        border: 1px solid #e2e8f0;
        padding: 16px;
        border-radius: 16px;
        box-shadow: 0 4px 16px rgba(15, 23, 42, 0.05);
    }

    .pro-card {
        background: white;
        border: 1px solid #e2e8f0;
        border-radius: 18px;
        padding: 18px;
        box-shadow: 0 6px 18px rgba(15, 23, 42, 0.05);
        margin-bottom: 14px;
    }

    .section-label {
        font-size: 0.82rem;
        font-weight: 700;
        color: #64748b;
        text-transform: uppercase;
        letter-spacing: 0.08em;
        margin-bottom: 8px;
    }

    .big-number {
        font-size: 1.8rem;
        font-weight: 700;
        color: #0f172a;
        margin-bottom: 4px;
    }

    .subtle-text {
        color: #64748b;
        font-size: 0.95rem;
    }

    .decision-badge {
        display: inline-block;
        padding: 6px 12px;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 700;
        letter-spacing: 0.03em;
    }

    .raise-badge {
        background: #dcfce7;
        color: #166534;
    }

    .discount-badge {
        background: #fef3c7;
        color: #92400e;
    }

    .hold-badge {
        background: #e0f2fe;
        color: #075985;
    }

    .insight-box {
        background: #eff6ff;
        border: 1px solid #bfdbfe;
        border-radius: 16px;
        padding: 14px 16px;
        color: #1e3a8a;
        margin-bottom: 12px;
    }
</style>
""", unsafe_allow_html=True)


# COLORS

ACTION_COLORS = {
    "RAISE": "#16a34a",
    "DISCOUNT": "#f59e0b",
    "HOLD": "#0ea5e9",
}

MAP_COLORS = {
    "RAISE": [22, 163, 74, 180],
    "DISCOUNT": [245, 158, 11, 180],
    "HOLD": [14, 165, 233, 180],
}


# DATA LOADING

@st.cache_data
def load_city_data(city):
    if city == "Washington DC":
        df = pd.read_csv("final_dc_airbnb_pricing.csv")
        events = pd.read_csv("dc_events_ticketmaster.csv")
    else:
        df = pd.read_csv("final_chicago_airbnb_pricing.csv")
        events = pd.read_csv("chicago_events_ticketmaster.csv")

    if "action" not in df.columns:
        df["action"] = "HOLD"

    if "recommended_price" not in df.columns:
        if "predicted_price" in df.columns:
            df["recommended_price"] = df["predicted_price"]
        elif "price_clean" in df.columns:
            df["recommended_price"] = df["price_clean"]
        else:
            df["recommended_price"] = np.nan

    for col in [
        "price_clean",
        "recommended_price",
        "predicted_price",
        "review_scores_rating",
        "accommodates",
        "bedrooms",
        "beds",
        "number_of_reviews",
        "nearest_event_distance_miles",
        "latitude",
        "longitude",
    ]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    if "recommended_price" in df.columns:
        df["recommended_price"] = df["recommended_price"].clip(upper=1000)

    if "neighbourhood" not in df.columns:
        if "neighbourhood_cleansed" in df.columns:
            df["neighbourhood"] = df["neighbourhood_cleansed"]
        else:
            df["neighbourhood"] = "Unknown"

    def demand_level(distance):
        if pd.isna(distance):
            return "LOW"
        if distance <= 0.5:
            return "VERY HIGH"
        if distance <= 1.5:
            return "HIGH"
        if distance <= 3:
            return "MEDIUM"
        return "LOW"

    if "nearest_event_distance_miles" in df.columns:
        df["event_demand"] = df["nearest_event_distance_miles"].apply(demand_level)
    else:
        df["event_demand"] = "LOW"

    def why_text(row):
        event_name = row.get("nearest_event_name", "a nearby event")
        dist = row.get("nearest_event_distance_miles", np.nan)
        action = row.get("action", "HOLD")
        if pd.notna(dist):
            return f"{action} because {event_name} is nearby ({dist:.2f} miles away)."
        return f"{action} based on listing and demand characteristics."

    df["why"] = df.apply(why_text, axis=1)

    if "date_local" in events.columns:
        events["date_local"] = pd.to_datetime(events["date_local"], errors="coerce")

    return df, events


@st.cache_data
def load_all_events():
    dc = pd.read_csv("dc_events_ticketmaster.csv")
    dc["city"] = "Washington DC"

    chicago = pd.read_csv("chicago_events_ticketmaster.csv")
    chicago["city"] = "Chicago"

    all_events = pd.concat([dc, chicago], ignore_index=True)

    if "date_local" in all_events.columns:
        all_events["date_local"] = pd.to_datetime(all_events["date_local"], errors="coerce")

    return all_events



# HELPERS


def get_comparable_listings(df, city_neighborhood, room_type, guests, bedrooms):
    comps = df.copy()

    if "neighbourhood" in comps.columns and city_neighborhood != "All":
        comps = comps[comps["neighbourhood"] == city_neighborhood]

    if "room_type" in comps.columns:
        comps = comps[comps["room_type"] == room_type]

    if "accommodates" in comps.columns:
        comps = comps[(comps["accommodates"].fillna(0) - guests).abs() <= 2]

    if "bedrooms" in comps.columns:
        comps = comps[(comps["bedrooms"].fillna(0) - bedrooms).abs() <= 1]

    return comps


def get_confidence_level(event_distance, comp_count):
    if pd.notna(event_distance) and event_distance <= 0.5 and comp_count >= 10:
        return "Very High"
    if pd.notna(event_distance) and event_distance <= 1.5 and comp_count >= 5:
        return "High"
    if pd.notna(event_distance) and event_distance <= 3:
        return "Medium"
    return "Low"


def get_market_position(current_price, market_median):
    if pd.isna(current_price) or pd.isna(market_median):
        return "Unknown"
    if current_price < market_median * 0.9:
        return "Below Market"
    if current_price > market_median * 1.1:
        return "Above Market"
    return "In Line with Market"

def summarize_weather(hourly_df):
    if hourly_df.empty:
        return {
            "avg_temp": np.nan,
            "total_precip": np.nan,
            "max_wind": np.nan,
            "avg_cloud": np.nan,
            "bad_weather_days": 0,
            "weather_score": 50,
        }

    daily = (
        hourly_df.assign(date=pd.to_datetime(hourly_df["time"]).dt.date)
        .groupby("date")
        .agg(
            avg_temp=("temperature_2m", "mean"),
            total_precip=("precipitation", "sum"),
            max_wind=("wind_speed_10m", "max"),
            avg_cloud=("cloud_cover", "mean"),
        )
        .reset_index()
    )

    daily["bad_weather"] = (
        (daily["total_precip"] >= 5) |
        (daily["max_wind"] >= 25)
    )

    avg_temp = daily["avg_temp"].mean()
    total_precip = daily["total_precip"].sum()
    max_wind = daily["max_wind"].max()
    avg_cloud = daily["avg_cloud"].mean()
    bad_weather_days = int(daily["bad_weather"].sum())

    score = 100
    score -= min(total_precip * 2, 30)
    score -= min(bad_weather_days * 10, 30)
    score -= min(max(max_wind - 15, 0), 20)
    score -= min(max((avg_cloud - 70) / 2, 0), 20)
    score = max(0, round(score))

    return {
        "avg_temp": round(avg_temp, 1) if pd.notna(avg_temp) else np.nan,
        "total_precip": round(total_precip, 1) if pd.notna(total_precip) else np.nan,
        "max_wind": round(max_wind, 1) if pd.notna(max_wind) else np.nan,
        "avg_cloud": round(avg_cloud, 1) if pd.notna(avg_cloud) else np.nan,
        "bad_weather_days": bad_weather_days,
        "weather_score": score,
    }

@st.cache_data(show_spinner=False)
def get_weather_for_booking(lat, lon, start_date, end_date):
    start_date = pd.to_datetime(start_date).date()
    end_date = pd.to_datetime(end_date).date()
    today = pd.Timestamp.today().date()

    hourly_vars = [
        "temperature_2m",
        "precipitation",
        "wind_speed_10m",
        "cloud_cover",
        "weather_code",
    ]

    # Open-Meteo forecast only works up to 16 days ahead
    max_forecast_date = today + pd.Timedelta(days=16)

    if end_date < today:
        base_url = "https://archive-api.open-meteo.com/v1/archive"
    elif start_date <= max_forecast_date and end_date <= max_forecast_date:
        base_url = "https://api.open-meteo.com/v1/forecast"
    else:
        # Too far ahead for forecast API
        return pd.DataFrame(), {
            "avg_temp": np.nan,
            "total_precip": np.nan,
            "max_wind": np.nan,
            "avg_cloud": np.nan,
            "bad_weather_days": 0,
            "weather_score": 50,
            "weather_note": "Weather forecast is only available up to 16 days ahead."
        }

    params = {
        "latitude": float(lat),
        "longitude": float(lon),
        "start_date": str(start_date),
        "end_date": str(end_date),
        "hourly": ",".join(hourly_vars),
        "timezone": "auto",
    }

    try:
        resp = requests.get(base_url, params=params, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except requests.RequestException:
        return pd.DataFrame(), {
            "avg_temp": np.nan,
            "total_precip": np.nan,
            "max_wind": np.nan,
            "avg_cloud": np.nan,
            "bad_weather_days": 0,
            "weather_score": 50,
            "weather_note": "Weather data could not be retrieved."
        }

    hourly = data.get("hourly", {})
    if not hourly or "time" not in hourly:
        return pd.DataFrame(), {
            "avg_temp": np.nan,
            "total_precip": np.nan,
            "max_wind": np.nan,
            "avg_cloud": np.nan,
            "bad_weather_days": 0,
            "weather_score": 50,
            "weather_note": "No weather data returned."
        }

    hourly_df = pd.DataFrame(hourly)
    summary = summarize_weather(hourly_df)
    summary["weather_note"] = ""
    return hourly_df, summary


def action_counts(df):
    return {
        "RAISE": int((df["action"] == "RAISE").sum()),
        "DISCOUNT": int((df["action"] == "DISCOUNT").sum()),
        "HOLD": int((df["action"] == "HOLD").sum()),
    }


def top_neighborhoods(df, n=6):
    return (
        df.groupby("neighbourhood")["recommended_price"]
        .median()
        .sort_values(ascending=False)
        .head(n)
        .sort_values()
    )


def estimate_uplift(row):
    current_price = row.get("price_clean", np.nan)
    recommended = row.get("recommended_price", np.nan)

    if pd.isna(current_price) or pd.isna(recommended):
        return np.nan

    monthly = (recommended - current_price) * 20
    annual = monthly * 12
    return annual


def compute_financial_impact(df, assumed_margin=0.35, event_nights=3):
    temp = df.copy()

    temp["nightly_uplift"] = temp["recommended_price"] - temp["price_clean"]
    temp["nightly_uplift"] = temp["nightly_uplift"].fillna(0)

    temp["percent_uplift"] = np.where(
        temp["price_clean"].fillna(0) > 0,
        temp["nightly_uplift"] / temp["price_clean"],
        0
    )

    temp["event_period_uplift"] = temp["nightly_uplift"] * event_nights
    temp["monthly_uplift"] = temp["nightly_uplift"] * 20
    temp["annual_uplift"] = temp["monthly_uplift"] * 12
    temp["gross_profit_uplift"] = temp["annual_uplift"] * assumed_margin

    baseline_annual_revenue = (temp["price_clean"].fillna(0) * 20 * 12).sum()
    projected_annual_revenue = (temp["recommended_price"].fillna(0) * 20 * 12).sum()

    summary = {
        "total_nightly_uplift": temp["nightly_uplift"].clip(lower=0).sum(),
        "total_event_period_uplift": temp["event_period_uplift"].clip(lower=0).sum(),
        "total_annual_uplift": temp["annual_uplift"].clip(lower=0).sum(),
        "total_gross_profit_uplift": temp["gross_profit_uplift"].clip(lower=0).sum(),
        "avg_percent_uplift": temp.loc[temp["nightly_uplift"] > 0, "percent_uplift"].mean() * 100 if (temp["nightly_uplift"] > 0).any() else 0,
        "baseline_annual_revenue": baseline_annual_revenue,
        "projected_annual_revenue": projected_annual_revenue,
    }

    neighborhood_view = (
        temp.groupby("neighbourhood")
        .agg(
            avg_current_price=("price_clean", "median"),
            avg_recommended_price=("recommended_price", "median"),
            nightly_uplift=("nightly_uplift", "sum"),
            event_period_uplift=("event_period_uplift", "sum"),
            annual_uplift=("annual_uplift", "sum"),
            gross_profit_uplift=("gross_profit_uplift", "sum"),
        )
        .sort_values("annual_uplift", ascending=False)
        .reset_index()
    )

    return summary, neighborhood_view


def build_price_calendar(selected_listing, city_events):
    current_price = selected_listing.get("price_clean", np.nan)
    listing_distance = selected_listing.get("nearest_event_distance_miles", np.nan)
    listing_demand = selected_listing.get("event_demand", "LOW")
    listing_event_name = selected_listing.get("nearest_event_name", "")

    events = city_events.copy()

    if "date_local" in events.columns:
        events = events.dropna(subset=["date_local"]).sort_values("date_local")

    if listing_event_name and "event_name" in events.columns:
        matched = events[events["event_name"] == listing_event_name].copy()
        others = events[events["event_name"] != listing_event_name].copy()
        events = pd.concat([matched, others], ignore_index=True)

    events = events.head(15).copy()

    def calendar_action(distance, event_type):
        event_type = str(event_type).lower()

        if pd.isna(distance):
            return "HOLD"
        if distance <= 0.5:
            return "RAISE"
        if distance <= 1.5 and event_type in ["music", "sports"]:
            return "RAISE"
        if distance <= 3:
            return "HOLD"
        return "DISCOUNT"

    def calendar_price(base_price, distance, event_type):
        if pd.isna(base_price):
            return np.nan

        event_type = str(event_type).lower()

        if pd.isna(distance):
            return round(base_price, 2)
        if distance <= 0.5:
            uplift = 0.20 if event_type in ["music", "sports"] else 0.12
            return round(base_price * (1 + uplift), 2)
        if distance <= 1.5:
            uplift = 0.12 if event_type in ["music", "sports"] else 0.07
            return round(base_price * (1 + uplift), 2)
        if distance <= 3:
            return round(base_price, 2)
        return round(base_price * 0.95, 2)

    calendar_rows = []

    for _, event in events.iterrows():
        event_name = event.get("event_name", "Unknown event")
        event_type = event.get("event_type", "Unknown")
        event_date = event.get("date_local", pd.NaT)

        distance = listing_distance
        demand = listing_demand

        rec_action = calendar_action(distance, event_type)
        rec_price = calendar_price(current_price, distance, event_type)

        if pd.notna(distance):
            if distance <= 0.5:
                strength = "very strong"
            elif distance <= 1.5:
                strength = "strong"
            elif distance <= 3:
                strength = "moderate"
            else:
                strength = "low"

            why = (
                f"{rec_action} price because {event_name} ({event_type}) is expected to drive {strength} demand. "
                f"This listing is approximately {distance:.2f} miles from the event, increasing booking pressure."
            )
        else:
            why = "HOLD price because no significant nearby event-driven demand is detected for this date."

        calendar_rows.append({
            "Date": event_date,
            "Event": event_name,
            "Event Type": event_type,
            "Distance (miles)": round(distance, 2) if pd.notna(distance) else np.nan,
            "Demand Level": demand,
            "Current Price": round(current_price, 2) if pd.notna(current_price) else np.nan,
            "Recommended Price": rec_price,
            "Action": rec_action,
            "Why": why,
        })

    calendar_df = pd.DataFrame(calendar_rows)

    if not calendar_df.empty and "Date" in calendar_df.columns:
        calendar_df = calendar_df.sort_values("Date")

    return calendar_df


def answer_question(question, df):
    q = question.lower()
    counts = action_counts(df)
    avg_price = df["recommended_price"].mean()

    if "raise" in q:
        top = df[df["action"] == "RAISE"][["name", "neighbourhood", "recommended_price"]].head(5)
        lines = "\n".join(
            f"- {r['name']} | {r['neighbourhood']} | ${r['recommended_price']:.0f}"
            for _, r in top.iterrows()
        )
        return f"{counts['RAISE']:,} listings should raise prices.\n\nTop examples:\n{lines}"

    if "discount" in q:
        return f"{counts['DISCOUNT']:,} listings should discount prices."

    if "hold" in q:
        return f"{counts['HOLD']:,} listings should hold prices."

    if "revenue" in q or "opportunity" in q:
        tmp = df.copy()
        tmp["annual_uplift"] = tmp.apply(estimate_uplift, axis=1)
        total = tmp["annual_uplift"].clip(lower=0).sum()
        return f"Estimated annual revenue opportunity is about ${total:,.0f} across the selected city."

    if "top neighbourhood" in q or "top neighborhood" in q:
        top = top_neighborhoods(df, 5)
        return "Top neighbourhoods by median recommended price:\n" + "\n".join(
            f"- {name}: ${value:,.0f}" for name, value in top.items()
        )

    if "overview" in q:
        return (
            f"There are {len(df):,} listings. "
            f"RAISE: {counts['RAISE']:,}, DISCOUNT: {counts['DISCOUNT']:,}, HOLD: {counts['HOLD']:,}. "
            f"Average recommended price is ${avg_price:,.0f}."
        )

    return "Try asking: which listings should raise prices, what is the revenue opportunity, or top neighbourhoods."



# APP HEADER

st.markdown("""
<div class="pro-card">
    <div class="section-label">Pricing Intelligence Platform</div>
    <div class="big-number" style="font-size:2.2rem;">PriceWise</div>
    <div class="subtle-text">
        Event-driven pricing recommendations for Airbnb hosts using machine learning,
        local event signals, comparables, and weather data.
    </div>
</div>
""", unsafe_allow_html=True)

city = st.sidebar.selectbox("Select city", ["Washington DC", "Chicago"])
df, city_events = load_city_data(city)
all_events = load_all_events()

counts = action_counts(df)

st.sidebar.markdown("### Quick Stats")
st.sidebar.write(f"📈 Raise: {counts['RAISE']:,}")
st.sidebar.write(f"📉 Discount: {counts['DISCOUNT']:,}")
st.sidebar.write(f"➖ Hold: {counts['HOLD']:,}")

tabs = st.tabs([
    "Dashboard",
    "Map View",
    "Event Calendar",
    "Price Calendar",
    "Listings Explorer",
    "Price Simulator",
    "Target Booking Dates",
    "Revenue Calculator",
    "Ask PriceWise",
])


# DASHBOARD

with tabs[0]:
    st.markdown("""
    <style>
    .dash-wrap {
        padding-top: 4px;
    }

    .topbar {
        background: #ffffff;
        border: 1px solid #e5e7eb;
        border-radius: 16px;
        padding: 14px 18px;
        margin-bottom: 16px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        box-shadow: 0 4px 12px rgba(15, 23, 42, 0.04);
    }

    .topbar-title {
        font-size: 1.15rem;
        font-weight: 700;
        color: #111827;
    }

    .topbar-sub {
        font-size: 0.85rem;
        color: #6b7280;
    }

    .metric-card {
        background: #ffffff;
        border: 1px solid #e5e7eb;
        border-radius: 16px;
        padding: 20px 22px;
        box-shadow: 0 4px 14px rgba(15, 23, 42, 0.04);
        min-height: 210px;
    }

    .metric-card.small {
        display: flex;
        flex-direction: column;
        justify-content: center;
        text-align: center;
    }

    .mini-label {
        color: #6b7280;
        font-size: 0.92rem;
        margin-bottom: 10px;
    }

    .mini-value {
        font-size: 2.2rem;
        font-weight: 700;
        color: #111827;
        line-height: 1.1;
        margin-bottom: 10px;
    }

    .mini-sub {
        color: #6b7280;
        font-size: 0.95rem;
        margin-top: 6px;
    }

    .section-card {
        background: #ffffff;
        border: 1px solid #e5e7eb;
        border-radius: 18px;
        padding: 18px;
        box-shadow: 0 4px 14px rgba(15, 23, 42, 0.04);
        min-height: 420px;
    }

    .rank-title {
        font-size: 1.08rem;
        font-weight: 700;
        color: #334155;
        margin-bottom: 14px;
    }

    .rank-item {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 12px;
        padding: 10px 0;
        border-bottom: 1px solid #f1f5f9;
    }

    .rank-left {
        display: flex;
        align-items: center;
        gap: 10px;
        width: 78%;
    }

    .rank-num {
        width: 26px;
        height: 26px;
        border-radius: 50%;
        background: #334155;
        color: white;
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 0.78rem;
        font-weight: 700;
        flex-shrink: 0;
    }

    .rank-shop {
        color: #475569;
        font-size: 0.92rem;
        line-height: 1.25;
    }

    .rank-val {
        color: #475569;
        font-size: 0.92rem;
        white-space: nowrap;
    }
    </style>
    """, unsafe_allow_html=True)

    total_sales = float(df["recommended_price"].fillna(0).sum())
    total_payments = int(len(df))
    avg_day_sales = total_sales / 10 if total_sales else 0
    conversion_rate = int((counts["RAISE"] / total_payments) * 100) if total_payments else 0

    st.markdown(f"""
    <div class="dash-wrap">
        <div class="topbar">
            <div>
                <div class="topbar-title">Dashboard</div>
                <div class="topbar-sub">Pricing performance overview for {city}</div>
            </div>
            <div class="topbar-sub">Model: Gradient Boosting</div>
        </div>
    </div>
    """, unsafe_allow_html=True)

    # top row
    c1, c2 = st.columns(2, gap="large")

    with c1:
        st.markdown(f"""
        <div class="metric-card small">
            <div class="mini-label">Total Revenue Opportunity</div>
            <div class="mini-value">${total_sales:,.0f}</div>
            <div class="mini-sub">Raise listings: {counts['RAISE']:,}</div>
            <div class="mini-sub">Estimated daily uplift: ${avg_day_sales:,.0f}</div>
        </div>
        """, unsafe_allow_html=True)

    with c2:
        st.markdown(f"""
        <div class="metric-card small">
            <div class="mini-label">Pricing Decisions</div>
            <div class="mini-value">{total_payments:,}</div>
            <div class="mini-sub">% listings recommended for price increase: {conversion_rate}%</div>
        </div>
        """, unsafe_allow_html=True)

    st.write("<div style='margin-top: 20px;'></div>", unsafe_allow_html=True)
    # bottom row
    left, right = st.columns(2, gap="large")

    with left:
        st.markdown('<div class="rank-title">Pricing Actions</div>', unsafe_allow_html=True)

        action_chart_df = (
            df["action"]
            .value_counts()
            .reindex(["RAISE", "DISCOUNT", "HOLD"])
            .fillna(0)
            .reset_index()
        )
        action_chart_df.columns = ["Action", "Count"]

        fig_actions = px.bar(
            action_chart_df,
            x="Action",
            y="Count",
            text="Count"
        )

        fig_actions.update_traces(
            textposition="outside",
            hovertemplate="<b>%{x}</b><br>Listings: %{y}<extra></extra>"
        )

        fig_actions.update_layout(
            height=300,
            margin=dict(l=10, r=10, t=10, b=10),
            xaxis_title="",
            yaxis_title="",
            showlegend=False
        )

        st.plotly_chart(
            fig_actions,
            use_container_width=True,
            config={"displayModeBar": False}
        )

    with right:
        st.markdown(
            '<div class="rank-title">Top Neighborhoods (Avg Price)</div>',
            unsafe_allow_html=True
        )

        ranking = (
            df.groupby("neighbourhood")["recommended_price"]
            .mean()
            .sort_values(ascending=False)
            .head(7)
        )

        for i, (name, value) in enumerate(ranking.items(), start=1):
            st.markdown(f"""
            <div class="rank-item">
                <div class="rank-left">
                    <div class="rank-num">{i}</div>
                    <div class="rank-shop">{name}</div>
                </div>
                <div class="rank-val">${value:,.0f}</div>
            </div>
            """, unsafe_allow_html=True)



# MAP VIEW

with tabs[1]:
    st.subheader(f"Map View — {city}")
    map_df = df.dropna(subset=["latitude", "longitude"]).copy()

    if map_df.empty:
        st.warning("No latitude/longitude data available.")
    else:
        map_df["color"] = map_df["action"].map(MAP_COLORS)

        deck = pdk.Deck(
            map_style="mapbox://styles/mapbox/light-v9",
            initial_view_state=pdk.ViewState(
                latitude=map_df["latitude"].mean(),
                longitude=map_df["longitude"].mean(),
                zoom=10,
                pitch=0,
            ),
            layers=[
                pdk.Layer(
                    "ScatterplotLayer",
                    data=map_df,
                    get_position='[longitude, latitude]',
                    get_fill_color="color",
                    get_radius=70,
                    pickable=True,
                )
            ],
            tooltip={
                "html": """
                <b>{name}</b><br/>
                Action: {action}<br/>
                Current Price: ${price_clean}<br/>
                Recommended Price: ${recommended_price}<br/>
                Event Demand: {event_demand}
                """,
                "style": {
                    "backgroundColor": "#ffffff",
                    "color": "#1f2937",
                    "border": "1px solid #d1d5db"
                },
            },
        )
        st.pydeck_chart(deck)


# EVENT CALENDAR

with tabs[2]:
    st.subheader("Event Calendar — DC + Chicago")
    events_view = all_events.sort_values("date_local")

    keep_cols = [
        "city",
        "date_local",
        "event_name",
        "event_type",
        "genre",
        "venue_name",
        "venue_city",
        "venue_state",
    ]
    keep_cols = [c for c in keep_cols if c in events_view.columns]

    st.dataframe(events_view[keep_cols], use_container_width=True, height=400)


# PRICE CALENDAR

with tabs[3]:
    st.subheader(f"Price Calendar — {city}")
    st.markdown("Generate an event-adjusted upcoming price calendar for a selected listing.")

    listing_options = df[["name"]].dropna().drop_duplicates()
    listing_name = st.selectbox(
        "Select a listing",
        listing_options["name"].sort_values().tolist(),
        key="price_calendar_listing"
    )

    selected_listing_df = df[df["name"] == listing_name].copy()

    if selected_listing_df.empty:
        st.warning("No listing found.")
    else:
        selected_listing = selected_listing_df.iloc[0]

        st.markdown("### Listing Summary")
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            current_price = selected_listing.get("price_clean", np.nan)
            st.metric("Current Price", f"${current_price:,.0f}" if pd.notna(current_price) else "N/A")
        with c2:
            rec_price = selected_listing.get("recommended_price", np.nan)
            st.metric("Recommended Price", f"${rec_price:,.0f}" if pd.notna(rec_price) else "N/A")
        with c3:
            st.metric("Action", str(selected_listing.get("action", "HOLD")))
        with c4:
            st.metric("Event Demand", str(selected_listing.get("event_demand", "LOW")))

        st.write(f"**Why:** {selected_listing.get('why', 'No explanation available.')}")

        calendar_df = build_price_calendar(selected_listing, city_events)

        if calendar_df.empty:
            st.info("No upcoming events available for calendar generation.")
        else:
            st.markdown("### Upcoming Event-Adjusted Pricing")

            for _, row in calendar_df.iterrows():
                action = row["Action"]

                if action == "RAISE":
                    badge_color = "#5BB98C"
                elif action == "DISCOUNT":
                    badge_color = "#F2A65A"
                else:
                    badge_color = "#6FA8DC"

                date_str = row["Date"].strftime("%b %d, %Y") if pd.notna(row["Date"]) else "Date N/A"
                rec_price = row["Recommended Price"]
                cur_price = row["Current Price"]

                rec_price_text = f"${rec_price:,.0f}" if pd.notna(rec_price) else "N/A"
                cur_price_text = f"${cur_price:,.0f}" if pd.notna(cur_price) else "N/A"

                with st.container(border=True):
                    top_left, top_right = st.columns([5, 1])

                    with top_left:
                        st.markdown(f"**{date_str}**")
                        st.write(row["Event"])

                    with top_right:
                        st.markdown(
                            f"""
                            <div style="
                                background-color:{badge_color};
                                color:white;
                                padding:4px 10px;
                                border-radius:999px;
                                text-align:center;
                                font-size:0.75rem;
                                font-weight:600;
                                width:fit-content;
                                margin-left:auto;
                            ">
                                {action}
                            </div>
                            """,
                            unsafe_allow_html=True
                        )

                    details_col1, details_col2 = st.columns(2)
                    with details_col1:
                        st.write(f"Recommended Price: {rec_price_text}")
                        st.caption(f"Current Price: {cur_price_text}")
                    with details_col2:
                        st.write(f"Distance: {row['Distance (miles)']} miles")
                        st.caption(f"Demand: {row['Demand Level']} | Event Type: {row['Event Type']}")

                    st.caption(row["Why"])

            st.markdown("### Calendar Action Breakdown")
            cal_counts = calendar_df["Action"].value_counts().reindex(["RAISE", "HOLD", "DISCOUNT"]).fillna(0)

            fig, ax = plt.subplots(figsize=(5, 3))
            cal_colors = [
                ACTION_COLORS.get("RAISE"),
                ACTION_COLORS.get("HOLD"),
                ACTION_COLORS.get("DISCOUNT"),
            ]
            ax.bar(cal_counts.index, cal_counts.values, color=cal_colors, edgecolor="none")
            ax.spines["top"].set_visible(False)
            ax.spines["right"].set_visible(False)
            ax.grid(axis="y", linestyle="--", alpha=0.25)
            ax.set_ylabel("Dates")
            st.pyplot(fig)


# LISTINGS EXPLORER

with tabs[4]:
    st.subheader(f"Listings Explorer — {city}")

    neighborhoods = ["All"] + sorted(df["neighbourhood"].dropna().unique().tolist())
    selected_neighborhood = st.selectbox("Neighbourhood", neighborhoods)

    min_price = st.slider("Minimum recommended price", 0, 1000, 50)
    selected_actions = st.multiselect(
        "Action type",
        ["RAISE", "DISCOUNT", "HOLD"],
        default=["RAISE", "DISCOUNT", "HOLD"],
    )

    filtered = df.copy()
    if selected_neighborhood != "All":
        filtered = filtered[filtered["neighbourhood"] == selected_neighborhood]
    filtered = filtered[filtered["recommended_price"] >= min_price]
    filtered = filtered[filtered["action"].isin(selected_actions)]

    show_cols = [
        "name",
        "neighbourhood",
        "price_clean",
        "recommended_price",
        "action",
        "event_demand",
        "why",
    ]
    show_cols = [c for c in show_cols if c in filtered.columns]

    st.dataframe(filtered[show_cols], use_container_width=True, height=450)


# PRICE SIMULATOR

with tabs[5]:
    st.subheader("Price Simulator")

    sim_city = st.selectbox("City", ["Washington DC", "Chicago"], key="sim_city")
    sim_neighborhood = st.text_input("Neighbourhood", "Downtown")
    sim_room_type = st.selectbox("Room type", ["Entire home/apt", "Private room", "Shared room"])
    sim_bedrooms = st.number_input("Bedrooms", 0, 10, 2)
    sim_guests = st.number_input("Guests", 1, 20, 4)
    sim_rating = st.slider("Rating", 3.0, 5.0, 4.7, 0.1)
    sim_distance = st.slider("Distance to nearest event (miles)", 0.0, 10.0, 1.0, 0.1)
    baseline_price = st.number_input("Current nightly price", 30, 2000, 180)

    if st.button("Simulate Price"):
        sim_df, _ = load_city_data(sim_city)

        if "room_type" in sim_df.columns:
            sim_df = sim_df[sim_df["room_type"] == sim_room_type]

        if "bedrooms" in sim_df.columns:
            sim_df = sim_df[(sim_df["bedrooms"].fillna(0) - sim_bedrooms).abs() <= 1]

        if "accommodates" in sim_df.columns:
            sim_df = sim_df[(sim_df["accommodates"].fillna(0) - sim_guests).abs() <= 2]

        if "review_scores_rating" in sim_df.columns:
            sim_df["rating_gap"] = (sim_df["review_scores_rating"].fillna(0) - sim_rating).abs()
        else:
            sim_df["rating_gap"] = 0

        if "nearest_event_distance_miles" in sim_df.columns:
            sim_df["distance_gap"] = (sim_df["nearest_event_distance_miles"].fillna(10) - sim_distance).abs()
        else:
            sim_df["distance_gap"] = 0

        sim_df["score"] = sim_df["rating_gap"] + sim_df["distance_gap"]
        sim_df = sim_df.sort_values("score").head(20)

        recommended = sim_df["recommended_price"].median() if not sim_df.empty else baseline_price

        if recommended > baseline_price * 1.1:
            sim_action = "RAISE"
        elif recommended < baseline_price * 0.9:
            sim_action = "DISCOUNT"
        else:
            sim_action = "HOLD"

        monthly_uplift = (recommended - baseline_price) * 20
        annual_uplift = monthly_uplift * 12

        if sim_distance <= 0.5:
            demand = "VERY HIGH"
        elif sim_distance <= 1.5:
            demand = "HIGH"
        elif sim_distance <= 3:
            demand = "MEDIUM"
        else:
            demand = "LOW"

        st.markdown(f"### Recommended Nightly Price: ${recommended:,.0f}")
        st.write(f"**Action:** {sim_action}")
        st.write(f"**Estimated Monthly Uplift:** ${monthly_uplift:,.0f}")
        st.write(f"**Estimated Annual Uplift:** ${annual_uplift:,.0f}")
        st.write(
            f"**Why:** {sim_room_type} listing in {sim_city}, {sim_neighborhood}, "
            f"{sim_bedrooms} bedrooms, for {sim_guests} guests, rating {sim_rating}, "
            f"with {demand} event demand based on {sim_distance:.1f} miles to the nearest event."
        )


# TARGET BOOKING DATES

with tabs[6]:
    st.subheader("Target Booking Dates")
    st.caption("Enter booking details to get a date-based pricing recommendation.")

    book_city = st.selectbox("City", ["Washington DC", "Chicago"], key="book_city")
    booking_df, booking_events = load_city_data(book_city)

    col1, col2 = st.columns(2)
    with col1:
        check_in = st.date_input("Check-in date", key="check_in")
        selected_event_type = st.selectbox(
            "Event type",
            ["Any", "Music", "Sports", "Arts & Theatre", "Miscellaneous"],
            key="booking_event_type"
        )
        booking_room_type = st.selectbox(
            "Room type",
            ["Entire home/apt", "Private room", "Shared room"],
            key="booking_room_type"
        )
        booking_neighborhoods = ["All"] + sorted(booking_df["neighbourhood"].dropna().unique().tolist())
        booking_neighborhood = st.selectbox("Neighbourhood", booking_neighborhoods, key="booking_neighborhood")

    with col2:
        check_out = st.date_input("Check-out date", key="check_out")
        booking_guests = st.number_input("Guests", 1, 20, 4, key="booking_guests")
        booking_bedrooms = st.number_input("Bedrooms", 0, 10, 2, key="booking_bedrooms")
        booking_current_price = st.number_input("Current nightly price", 30, 5000, 180, key="booking_current_price")

    if st.button("Generate Booking Recommendation"):
        stay_nights = max((check_out - check_in).days, 1)

        comps = get_comparable_listings(
            booking_df,
            booking_neighborhood,
            booking_room_type,
            booking_guests,
            booking_bedrooms
        )

        if selected_event_type != "Any" and "event_type" in booking_events.columns:
            filtered_events = booking_events[
                booking_events["event_type"].astype(str).str.lower() == selected_event_type.lower()
            ].copy()
        else:
            filtered_events = booking_events.copy()

        if "date_local" in filtered_events.columns:
            filtered_events["date_only"] = pd.to_datetime(filtered_events["date_local"], errors="coerce").dt.date
            booking_events_near_date = filtered_events[
                (filtered_events["date_only"] >= check_in) & (filtered_events["date_only"] <= check_out)
            ].copy()
        else:
            booking_events_near_date = filtered_events.copy()

        market_median = comps["price_clean"].median() if not comps.empty else np.nan
        recommended_price = comps["recommended_price"].median() if not comps.empty else booking_current_price

        event_count = len(booking_events_near_date)

        if selected_event_type == "Music":
            recommended_price *= 1.08
        elif selected_event_type == "Sports":
            recommended_price *= 1.10
        elif selected_event_type == "Arts & Theatre":
            recommended_price *= 1.04
        elif selected_event_type == "Miscellaneous":
            recommended_price *= 1.02

        if event_count >= 3:
            recommended_price *= 1.08
        elif event_count == 2:
            recommended_price *= 1.05
        elif event_count == 1:
            recommended_price *= 1.03

        selected_listing_for_weather = comps.dropna(subset=["latitude", "longitude"]).head(1)

        if not selected_listing_for_weather.empty:
            weather_lat = selected_listing_for_weather.iloc[0]["latitude"]
            weather_lon = selected_listing_for_weather.iloc[0]["longitude"]
        else:
            city_coords = {
                "Washington DC": (38.9072, -77.0369),
                "Chicago": (41.8781, -87.6298),
            }
            weather_lat, weather_lon = city_coords[book_city]

        weather_hourly, weather_summary = get_weather_for_booking(
            weather_lat,
            weather_lon,
            check_in,
            check_out
        )

        if weather_summary.get("weather_note"):
            st.info(weather_summary["weather_note"])


        weather_score = weather_summary["weather_score"]
        bad_weather_days = weather_summary["bad_weather_days"]

        if weather_score >= 80:
            recommended_price *= 1.03
        elif weather_score <= 40:
            recommended_price *= 0.92
        elif weather_score <= 60:
            recommended_price *= 0.97

        recommended_price = round(recommended_price, 2)

        if booking_current_price > 0:
            suggested_increase_pct = ((recommended_price - booking_current_price) / booking_current_price) * 100
        else:
            suggested_increase_pct = 0

        if suggested_increase_pct > 10:
            booking_action = "RAISE"
        elif suggested_increase_pct < -10:
            booking_action = "DISCOUNT"
        else:
            booking_action = "HOLD"

        if "nearest_event_distance_miles" in comps.columns and not comps.empty:
            avg_event_distance = comps["nearest_event_distance_miles"].median()
        else:
            avg_event_distance = np.nan

        confidence = get_confidence_level(avg_event_distance, len(comps))
        market_position = get_market_position(booking_current_price, market_median)

        current_stay_revenue = booking_current_price * stay_nights
        projected_stay_revenue = recommended_price * stay_nights
        revenue_gain = projected_stay_revenue - current_stay_revenue

        st.markdown("### Booking Recommendation")

        badge_class = "hold-badge"
        if booking_action == "RAISE":
            badge_class = "raise-badge"
        elif booking_action == "DISCOUNT":
            badge_class = "discount-badge"

        st.markdown(
            f"""
            <div class="pro-card">
                <div class="section-label">Recommended Action</div>
                <div style="display:flex; justify-content:space-between; align-items:center; gap:12px;">
                    <div>
                        <div class="big-number">${recommended_price:,.0f}</div>
                        <div class="subtle-text">
                            Suggested nightly rate for this booking window
                        </div>
                    </div>
                    <div class="decision-badge {badge_class}">
                        {booking_action}
                    </div>
                </div>
            </div>
            """,
            unsafe_allow_html=True
        )




        if booking_action == "RAISE":
            st.success("Recommendation: Increase price for this booking window")
        elif booking_action == "DISCOUNT":
            st.warning("Recommendation: Lower price to stay competitive")
        else:
            st.info("Recommendation: Keep current pricing")

        m1, m2, m3, m4 = st.columns(4)
        with m1:
            st.metric("Recommended Nightly Price", f"${recommended_price:,.0f}")
        with m2:
            st.metric("Suggested Rate Change", f"{suggested_increase_pct:.1f}%")
        with m3:
            st.metric("Confidence Level", confidence)
        with m4:
            st.metric("Market Position", market_position)

        m5, m6, m7 = st.columns(3)
        with m5:
            st.metric("Current Stay Revenue", f"${current_stay_revenue:,.0f}")
        with m6:
            st.metric("Projected Stay Revenue", f"${projected_stay_revenue:,.0f}")
        with m7:
            if revenue_gain >= 0:
                st.metric("Revenue Opportunity", f"+${revenue_gain:,.0f}")
            else:
                st.metric("Revenue Risk", f"-${abs(revenue_gain):,.0f}")

        st.caption(
          f"Confidence: {confidence} — based on {len(comps)} comparable listings, "
          f"event proximity, and consistency of market signals."
        )


        st.markdown(
            f"""
            <div class="insight-box">
                For this {stay_nights}-night stay in <strong>{book_city}</strong>, the model recommends
                a <strong>{booking_action.lower()}</strong> decision based on event activity,
                comparable listings, market position, and a weather score of
                <strong>{weather_summary['weather_score']}/100</strong>.
            </div>
            """,
            unsafe_allow_html=True
          )

        if not pd.isna(market_median):
            st.write(f"Comparable market median nightly price: ${market_median:,.0f}")

        if event_count > 0:
            st.write(f"Detected {event_count} relevant event(s) during the selected booking window.")
        else:
            st.write("No major matching events were detected during the selected booking window.")

        st.markdown("### Weather Outlook")

        if weather_score >= 80:
          weather_label = "Strong Positive Demand Signal"
        elif weather_score >= 60:
          weather_label = "Moderate Positive Demand"
        elif weather_score >= 40:
          weather_label = "Neutral Impact"
        else:
          weather_label = "Demand Risk (Weather Impact)"

        st.info(
          f"Weather Impact: {weather_label}. "
          f"This booking window has a weather score of {weather_score}/100, "
          f"which {'supports higher pricing' if weather_score >= 60 else 'may suppress demand'}."
        )

        if weather_score >= 80:
            st.success("☀️ Strong Demand Weather Conditions")
        elif weather_score >= 60:
            st.info("🌤️ Favorable Weather Conditions")
        elif weather_score >= 40:
            st.warning("🌥️ Neutral Weather Impact")
        else:
            st.error("🌧️ Weather Risk – Demand May Drop")


        st.markdown("### Key Drivers of Recommendation")

        drivers = []

        if event_count > 0:
          drivers.append(f"{event_count} nearby event(s) increasing demand")

        if len(comps) > 0:
          drivers.append(f"{len(comps)} comparable listings used for pricing baseline")

        if weather_score >= 70:
          drivers.append("Favorable weather conditions boosting demand")
        elif weather_score <= 50:
          drivers.append("Weather conditions reducing expected demand")

        for d in drivers:
          st.write(f"- {d}")


        w1, w2, w3, w4, w5 = st.columns(5)

        with w1:
            st.markdown("<div class='weather-label'>Weather Score</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='weather-metric'>{weather_summary['weather_score']}/100</div>", unsafe_allow_html=True)

        with w2:
            st.markdown("<div class='weather-label'>Avg Temp</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='weather-metric'>{weather_summary['avg_temp']}°C</div>", unsafe_allow_html=True)

        with w3:
            st.markdown("<div class='weather-label'>Total Precip</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='weather-metric'>{weather_summary['total_precip']} mm</div>", unsafe_allow_html=True)

        with w4:
            st.markdown("<div class='weather-label'>Max Wind</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='weather-metric'>{weather_summary['max_wind']} km/h</div>", unsafe_allow_html=True)

        with w5:
            st.markdown("<div class='weather-label'>Bad Weather Days</div>", unsafe_allow_html=True)
            st.markdown(f"<div class='weather-metric'>{weather_summary['bad_weather_days']}</div>", unsafe_allow_html=True)


        if not booking_events_near_date.empty:
            show_event_cols = [c for c in ["date_local", "event_name", "event_type", "venue_name"] if c in booking_events_near_date.columns]
            st.markdown("### Events in Booking Window")
            st.dataframe(
                booking_events_near_date[show_event_cols].head(10),
                use_container_width=True,
                height=250
            )

        if not comps.empty:
            show_comp_cols = [c for c in ["name", "neighbourhood", "room_type", "price_clean", "recommended_price"] if c in comps.columns]
            st.markdown("### Comparable Listings")
            st.dataframe(
                comps[show_comp_cols].head(10),
                use_container_width=True,
                height=250
            )

        if not weather_hourly.empty:
            with st.expander("View Detailed Weather Data"):
                show_weather_cols = [c for c in ["time", "temperature_2m", "precipitation", "wind_speed_10m", "cloud_cover"] if c in weather_hourly.columns]
                st.dataframe(
                    weather_hourly[show_weather_cols].head(24),
                    use_container_width=True
            )


# REVENUE CALCULATOR

with tabs[7]:
    st.subheader(f"Revenue Calculator — {city}")

    rev_df = df.copy()
    rev_df["annual_uplift"] = rev_df.apply(estimate_uplift, axis=1)
    rev_df["annual_uplift"] = rev_df["annual_uplift"].clip(lower=0)

    total_uplift = rev_df["annual_uplift"].sum()
    st.metric("Estimated Annual Revenue Opportunity", f"${total_uplift:,.0f}")

    by_neighborhood = (
        rev_df.groupby("neighbourhood")
        .agg(
            avg_current_price=("price_clean", "median"),
            avg_recommended_price=("recommended_price", "median"),
            estimated_annual_gain=("annual_uplift", "sum"),
        )
        .sort_values("estimated_annual_gain", ascending=False)
        .head(10)
        .reset_index()
    )

    st.dataframe(by_neighborhood, use_container_width=True)


# ASK PRICEWISE

with tabs[8]:
    st.subheader("Ask PriceWise")

    user_q = st.text_input(
        "Ask a question",
        placeholder="Which listings should raise prices? What is the revenue opportunity? Top neighbourhoods?",
    )

    if st.button("Ask"):
        if user_q.strip():
            st.write(answer_question(user_q, df))
        else:
            st.warning("Please enter a question.")